<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Article;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param Article $article
	 * @param         $searchString
	 *
	 * @return array
	 */
	public function getSearch($searchString)
	{
		return $this->createQueryBuilder('a')
		            ->where('a.title LIKE :param')
		            ->setParameter('param', '%' . $searchString . '%')
		            ->getQuery()
		            ->getResult();
	}
}